package com.sololaunches.www.keralarailandmetro;

/**
 * Created by hp on 7/3/2017.
 */

public class QueryCreator {


    public static String getCreateRailwayMainQuery() {
        String[] stations = ArrayHolder.getStations();


        String query = "CREATE TABLE RL_STATIONS_TRAIN_MAIN ( MAIN_ID INTEGER PRIMARY KEY AUTOINCREMENT,TRAIN_NUMBER TEXT,TRAIN_NAME TEXT,UPDATED_ON TEXT," +
                "STN1 TEXT,STN2 TEXT,STN3 TEXT,STN4 TEXT,STN5 TEXT,STN6 TEXT,STN7 TEXT,STN8 TEXT,STN9 TEXT,STN10 TEXT," +
                "STN11 TEXT,STN12 TEXT,STN13 TEXT,STN14 TEXT,STN15 TEXT,STN16 TEXT,STN17 TEXT,STN18 TEXT,STN19 TEXT,STN20 TEXT," +
                "STN21 TEXT,STN22 TEXT,STN23 TEXT,STN24 TEXT,STN25 TEXT,STN26 TEXT,STN27 TEXT,STN28 TEXT,STN29 TEXT,STN30 TEXT," +
                "STN31 TEXT,STN32 TEXT,STN33 TEXT,STN34 TEXT,STN35 TEXT,STN36 TEXT,STN37 TEXT,STN38 TEXT,STN39 TEXT,STN40 TEXT," +
                "STN41 TEXT,STN42 TEXT,STN43 TEXT,STN44 TEXT,STN45 TEXT,STN46 TEXT,STN47 TEXT,STN48 TEXT,STN49 TEXT,STN50 TEXT," +
                "STN51 TEXT,STN52 TEXT,STN53 TEXT,STN54 TEXT,STN55 TEXT,STN56 TEXT,STN57 TEXT,STN58 TEXT,STN59 TEXT,STN60 TEXT," +
                "STN61 TEXT,STN62 TEXT,STN63 TEXT,STN64 TEXT,STN65 TEXT,STN66 TEXT,STN67 TEXT,STN68 TEXT,STN69 TEXT,STN70 TEXT," +
                "STN71 TEXT,STN72 TEXT,STN73 TEXT,STN74 TEXT,STN75 TEXT,STN76 TEXT,STN77 TEXT,STN78 TEXT,STN79 TEXT,STN80 TEXT," +
                "STN81 TEXT,STN82 TEXT,STN83 TEXT,STN84 TEXT,STN85 TEXT,STN86 TEXT,STN87 TEXT,STN88 TEXT,STN89 TEXT,STN90 TEXT," +
                "STN91 TEXT,STN92 TEXT,STN93 TEXT,STN94 TEXT,STN95 TEXT,STN96 TEXT,STN97 TEXT,STN98 TEXT,STN99 TEXT,STN100 TEXT);";


        return query;

    }


    public static String getCreateMetroQuery() {

        String query = "CREATE TABLE METRO_MAIN (TRAIN_ID INTEGER PRIMARY KEY AUTOINCREMENT,TRAIN TEXT,STATION TEXT,WEEKEND TEXT,AUV TEXT,PCD TEXT,CPD TEXT,ABK TEXT,MTM TEXT,KLMR TEXT,CUSAT TEXT,PTP Text,IPL Text,CSKP Text,PLV Text,JLNS Text,KLR Text,LIS Text,MGR Text,MRJ Text,ERS Text,KDV Text,ELM Text,VYT Text,TYK Text,EKP Text);";

        return query;
    }
}
